// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/python-ide-replit/Current.tsx": () => import("../components/mockups/python-ide-replit/Current.tsx"),
  "./components/mockups/python-ide-replit/ReplitWorkspace.tsx": () => import("../components/mockups/python-ide-replit/ReplitWorkspace.tsx")
};
